services:
  asir_bind9:
    container_name: asir_DNS1
    image: internetsystemsconsortium/bind9:9.16
    ports:
      - 53:53
    networks:
      bind9_subnet:
        ipv4_address: 172.28.5.3
    volumes:
      - ./conf:/etc/bind
      - ./zonas:/var/lib/bind
  asir_cliente:
    container_name: asir_cliente
    image: alpine
    networks:
      bind9_subnet:
        ipv4_address: 172.28.5.8
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    dns:
      - 172.28.5.3  # el contenedor dns server
networks:
  bind9_subnet: 
    external: true
#Otra forma de hacerlo
##networks:
   ##network:
      ##ipam:
        ##config:
          ##subnet: 172.28.0.0/24
          ##gateway: 172.28.0.1